name: Run TypeCheck

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "tsc"
  cancel-in-progress: false

jobs:
  tsc-n-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install Deps
        run: bun install
      - name: Run tsc
        run: bun tsc --noEmit
      - name: Run Build Script
        run: bun run build
